---
title: "writing_functions"
output: html_document
date: "2024-11-15"
---

```{r message = FALSE}
library(tidyverse)
library(rvest)
library(httr)
library(ggridges)
library(patchwork)
library(scales)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Do something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a function to compute z-scores.

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric.")
  }
  
  if(length(x)<3){
    stop("Input must have at least 3 numbers.")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_scores(x_vec)

```

```{r, error = TRUE}
z_scores(3)
z_scores("my name is laura")
z_scores(mtcars)
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

## Multiple outputs
```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric.")
  }
  
  if(length(x)<3){
    stop("Input must have at least 3 numbers.")
  }
  
 mean_x = mean(x)
 sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}

z_scores(x_vec)
```

```{r}
x_vec = rnorm(100, mean = 3, sd = 4)
mean_and_sd(x_vec)
```

## Multiple inputs

I'd like to do this with a function.
```{r}
sim_data = 
  tibble(
    x = rnorm(n = 100, mean = 4, sd = 4)
  )

sim_data %>%
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
```

```{r}
sim_mean_sd = function (samp_size, mu=3, sigma=3)  {
  
  sim_data = 
  tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma)
  )

sim_data %>%
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
}

sim_mean_sd(samp_size=100,mu=6,sigma=3)
sim_mean_sd(100)
```

You can set default values like above, but don't need to. So in the instance above, if mu isn't specified, it would default to 3. But if one is specified then it will go with the specified one.

## review napolean dynamite








